### ISSUE TITLE
Go build does not work

### ISSUE THREAD

**Issue by shan-96** [ksysoev/deriv-api-bff#3]
```sh
$ go build
no Go files in ...
```

`go build` currently fails for me with this error.

`go build ./...` works.

The impact is that either with or without `./...` the package does not get copied to `$GOROOT/pkg/..` leading to other issues.

Have you faced it?

**Comment by shan-96** [comment]
> @shan-96 not sure, why do you need go root? I usually use go workspace

@ksysoev not sure I follow. I am running `go build` from workspace i.e. repository root. But I am expecting the build to be copied at `$GOROOT/pkg/..` is that not correct?

**Comment by ksysoev** [comment]
@shan-96 based on documentation it shouldn't install packages just compile:

> Build compiles the packages named by the import paths, along with their dependencies, but it does not install the results.

https://pkg.go.dev/cmd/go#hdr-Compile_packages_and_dependencies

**Comment by shan-96** [comment]
ok so I original could not run `mockery --all` for this repo. (I still cannot) but I am able to build, so I will solve it later when we need more mocks
