### ISSUE TITLE
Load calls configuration from etcd on start

### ISSUE THREAD

**Issue by ksysoev** [ksysoev/deriv-api-bff#41]
Not fully sure it's possible, but viper has built in support for reading configuration from etcd. If not possible just implement logic in call repo to read call configuration from etcd and call it on start.

**Comment by shan-96** [comment]
@ksysoev this can be taken care of in this manner

- use viper to load config (done)
- send loaded config to etcd (done)
- add watcher to viper to watch config file changes (done)
- add watcher to etcd to watch call repo config (todo)
- add source based resolver to help avoid different sources of truth (todo)
